### PR TITLE
Restores support for repos in subgroups

### LINKED ISSUE #19: Subgroups are not handled
Hi,

Our org switched to subgroups, and this step doesn't support them.

This regexp is the culprit: https://github.com/bitrise-steplib/steps-gitlab-status/blob/master/main.go#L30-L36

Our URL look like this:

`https://gitlab.foobar.com/group/subgroup/repo.git` , and the resulting status URL is 
`https://gitlab.foobar.com/api/v4/projects/subgroup%2Frepo/statuses/<hash>`

I'm not sure what's the best way to handle this. I would not mind an environment variable that doesn't attempt to parse an url, but simply expects "group/subgroup/repo" to be well formed.

### PR DESCRIPTION
**Pull request by usmonster**
Fixes bitrise-steplib/steps-gitlab-status#19

### CODE REVIEW

**Comment by usmonster** [comment]
No pressure, but please feel free to check when you have a chance, @trapacska or @lpusok. 🙏Thanks!

**Comment by mackoj** [comment]
@usmonster should you add an http with subgroup test ?

**Comment by mackoj** [comment]
Thanks !

**Comment by usmonster** [comment]
Just a friendly reminder ping for @trapacska or @lpusok to take a quick look, please. 

Thanks again in advance!

**Comment by istx25** [comment]
@usmonster I have shared this with the engineering team and they will take a look at this in the next sprint (starting Thursday).

**Review by Szabadember — APPROVED** [review]

**Pull request merged**
